In [ ]:
# question 1
import numpy as n;

array1 = n.empty((2,2), dtype="int64");

print(array1);



[[      374119333               0]
 [       10755872 132642875826288]]


In [ ]:
# question 2
import numpy as n;

array1 = n.ones((4,2), dtype=n.int64);

print(array1);

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# question 3
import numpy as n;
array1 = n.full((3,3),9,dtype=n.int64);
print(array1);


[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
# question 4
import numpy as n;

array1 = n.zeros((3,3),dtype=n.int64);
print(array1);


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# question 5
import numpy as n;
array1 = n.ones((3,3),dtype=n.int64);
print(array1);


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# question 6
import numpy as n;
new_list = [1,2,3,4];

array1 = n.array(new_list);
print(array1);


[1 2 3 4]


In [ ]:
# question 7
import numpy as n ;


array1 = n.arange(10,49);
print(array1);


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
# question 8
import numpy as n ;


array1 = n.arange(9).reshape(3, 3);
print(array1);


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# question 9
import numpy as n ;


array1 = n.eye(3,3 ,dtype=n.int64);
print(array1);


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# question 10
import numpy as n ;


array1 = n.random.random(30);

#print(array1);
print("----------------------------------------------------------");
print(f"the mean of the given numpy array is : {array1.mean()}");


----------------------------------------------------------
the mean of the given numpy array is : 0.5143167958550566


In [ ]:
# question 11
import numpy as n ;


matrix1 = n.random.random(100).reshape(10,10);
#print(matrix1);

min_matrix=matrix1.min();
max_matrix=matrix1.max();

print(f"The minimum vale of  matrix is : {min_matrix}");
print(f"The maximum vale of  matrix is : {max_matrix}");




The minimum vale of  matrix is : 0.012461206308359896
The maximum vale of  matrix is : 0.9738746937076282


In [ ]:
# question 12
import numpy as np;

array1=np.zeros(10, dtype=np.int64)
print(array1)

array1[4]=1
print("------------------------------")
print(array1)



[0 0 0 0 0 0 0 0 0 0]
------------------------------
[0 0 0 0 1 0 0 0 0 0]


In [ ]:
# question 13
import numpy as n;

arr = [1,2,0,0,4,0];

array1=n.array(arr);

#print(array1)
reversed_array1=np.flip(array1)
print("reversed array :")
print(reversed_array1)

reversed array :
[0 4 0 0 2 1]


In [ ]:
# question 14
import numpy as n

n2darray=np.ones((3,3),dtype=n.int64);
n2darray[1:-1, 1:-1] = 0

print(n2darray)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [ ]:
#Q15
import numpy as np

# Create an 8x8 array of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill 1s in alternating positions
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#problem 3: array operation
import numpy as n
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

#sub q1 adding two numpy arrays
sumX_Y=(x+y);
print(f"The sum of numpu array x and y is :{sumX_Y}");

#sub q2 adding two numpy arraysSubtract the two array.
subV_W=(v-w);
print(f"The difference  of numpu array v-w  is :{subV_W}");

#sub q3 Multiply the array with any integers
multiply=x*9
print(f"array x multiplyed by scaler integer 9 :{multiply}");

#sub Q4 Finding the square of each element of the array.

squareArrY=y**2
print(f"Square of the array y is :{squareArrY}");

#sub Q5
vDotw=np.dot(v,w);
xdotv=np.dot(x,v);
xdoty=np.dot(x,y)
print(f"Dot of v,w  is :{vDotw}");
print(f"Dot of x,v  is:{xdotv}");
print(f"Dot of x,y  is:{xdoty}");


#q6

conCatX_y_row=np.concatenate((x,y),axis=0)
conCatV_w_col=np.concatenate((v.reshape(2,1),w.reshape(2,1)),axis=1)
print(conCatX_y_row)
print(conCatV_w_col)


#Q7
#...........conCatX_v=np.concat((x,v))................
# this generates the arror
"""ValueError: all the input arrays must
have same number of dimensions,
but the array at index 0 has 2
 dimension(s) and the array at index 1 has 1 dimension(s)"""

#Explaination:
"""This error occurs because to concatenate two array togather
their dimention must be equal 1d array and 2d array cant concatenated
togather """
#to solve this problem we neew to  reshape the v array


conCatX_v=np.concatenate((x,v.reshape(1,2)),axis=0)
print(f"corected after reshape:\n{conCatX_v}")















The sum of numpu array x and y is :[[ 6  8]
 [10 13]]
The difference  of numpu array v-w  is :[-2 -2]
array x multiplyed by scaler integer 9 :[[ 9 18]
 [27 45]]
Square of the array y is :[[25 36]
 [49 64]]
Dot of v,w  is :219
Dot of x,v  is:[29 77]
Dot of x,y  is:[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
corected after reshape:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
#task 4 matrix operation
import numpy as n;

a = n.array([[3,4],[7,8]]);
b = n.array([[5,3],[2,1]]);

aInverse=n.linalg.inv(a)
adotAInverse=n.dot(a,aInverse)

print(n.round( adotAInverse))
#The value 1.77635684e-15 is extremely small (almost zero).
#This happens due to floating-point rounding error in NumPy.
#So rounding it gives the exact identity matrix:

#Prove AB ̸= BA
adotB=n.dot(a,b);
bdotA = n.dot(b,a);

if adotB.all==bdotA.all:
  print(" AB = BA");

else:
  print("---------------------")
  print("AB ̸= BA")


#Prove (ab) transpose = b transpose a transpose

abT=adotB.T;
aT= a.T;
bT= b.T;

bTdotAT=n.dot(bT,aT)



if n.array_equal(abT,bTdotAT):
    print("\n(AB)T = BT AT")
else:
    print("\nThey are NOT equal")









[[1. 0.]
 [0. 1.]]
---------------------
AB ̸= BA

(AB)T = BT AT


In [ ]:
#linear algebra with matrix
import numpy as n
""" 2x − 3y + z = −1
    x − y + 2z = −3
    3x + y − z = 9   """

a=n.array([[2, -3, 1],
          [1, -1, 2],
          [3, 1, -1]],dtype=float);

b=n.array([-1, -3, 9],dtype=float);


aInverse=n.linalg.inv(a)

solution=n.dot(aInverse, b);
x=solution[0]
y=solution[1]
z=solution[2]
print(f"x:{x}, y:{y}, z:{z}")





x:2.0, y:1.0, z:-2.0


In [ ]:
#4.1 element wise adition
import numpy as n
import time

size=1000000
l1=list(range(size))
l2=list(range(size))


pL_initial_time=time.time()
sum1=[]
for i in range (len(l1)):
  local11= l1[i]+l2[i]
  sum1.append(local11)


pL_end_time=time.time();
print("the sum using pyton listis ",sum1[:100])

total_time1=(pL_end_time-pL_initial_time)
print(f"total time python list operation{total_time1}, seconds")


nparray1=n.array(l1)
nparray2=n.array(l2)

np_initial_time=time.time();

arr_sum=(nparray1+nparray2)

np_end_time=time.time();

print("the sum using numpy array  ",arr_sum[:100])

np_totaltime=np_end_time-np_initial_time
print(f"total time taken bu numppy array{np_totaltime}, seconds")






the sum using pyton listis  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
total time python list operation0.21348166465759277, seconds
the sum using numpy array   [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
total time taken bu numppy arr

In [ ]:
#4.1 element wise multiplication
import numpy as n
import time

size=1000000
l1=list(range(size))
l2=list(range(size))


pL_initial_time=time.time()

mul1 =[]
for i in range (len(l1)):
  local1=l1[i]*l2[i]
  mul1.append(local1)


pL_end_time=time.time();
print("First 5 elements (Python list):", mul1[:100])


total_time1=(pL_end_time-pL_initial_time)
print(f"total time python list operation{total_time1}, seconds")


nparray1=n.array(l1)
nparray2=n.array(l2)

np_initial_time=time.time();

arr_mul=(nparray1*nparray2)

np_end_time=time.time();

print("the product using numpy array  ",arr_mul[:100])

np_totaltime=np_end_time-np_initial_time
print(f"total time taken bu numppy array{np_totaltime}, seconds")






First 5 elements (Python list): [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]
total time python list operation0.23045969009399414, seconds
the product using numpy array   [   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 

In [ ]:

#4.1 dot product
import numpy as n
import time

size=1000000
l1=list(range(size))
l2=list(range(size))


pL_initial_time=time.time()

mul1 =0
for i in range (len(l1)):
  mul1+= l1[i]*l2[i]


pL_end_time=time.time();
print("First 5 elements (Python list):", mul1)


total_time1=(pL_end_time-pL_initial_time)
print(f"total time python list operation{total_time1}, seconds")


nparray1=n.array(l1)
nparray2=n.array(l2)

np_initial_time=time.time();

arr_mul=n.sum(nparray1*nparray2)

np_end_time=time.time();

print("the product using numpy array  ",arr_mul)

np_totaltime=np_end_time-np_initial_time
print(f"total time taken bu numppy array{np_totaltime}, seconds")






First 5 elements (Python list): 333332833333500000
total time python list operation0.23664116859436035, seconds
the product using numpy array   333332833333500000
total time taken bu numppy array0.0038950443267822266, seconds


In [ ]:
import numpy as n
import random
import time

size = 1000
# Matrix 1
matrix1 = []
for i in range(size):
    row = []
    for j in range(size):
        row.append(random.randint(0, 9))
    matrix1.append(row)

# Matrix 2
matrix2 = []
for i in range(size):
    row = []
    for j in range(size):
        row.append(random.randint(0, 9))
    matrix2.append(row)

print("Top-left 2x2 of matrix1:")
print([row[:2] for row in matrix1])
print("Top-left 2x2 of matrix2:")
print([row[:2] for row in matrix2])

# -----------------------------
# 2. Element-wise multiplication
# -----------------------------
print("\nPerforming element-wise multiplication...")

start_time = time.time()

# Initialize result matrix
elementwise_result = []
for i in range(size):
    row = []
    for j in range(size):
        row.append(matrix1[i][j] * matrix2[i][j])
    elementwise_result.append(row)

end_time = time.time()
print("Top-left 2x2 of element-wise multiplication result:")
print([row[:2] for row in elementwise_result])
print(f"Time taken for element-wise multiplication: {end_time - start_time:.5f} seconds")

# -----------------------------
# 3. Matrix multiplication
# -----------------------------
print("\nPerforming matrix multiplication using numpy")

start_time = time.time()

matrix_mult_resuld= n.dot(matrix1,matrix2)

end_time = time.time()
print("Top-left 2x2 of matrix multiplication result:")
print([row[:2] for row in matrix_mult_result])
print(f"Time taken for matrix multiplication: {end_time - start_time:.5f} seconds")


Top-left 2x2 of matrix1:
[[8, 1], [8, 4], [1, 5], [2, 4], [5, 4], [8, 6], [8, 0], [2, 5], [8, 2], [9, 6], [6, 5], [3, 0], [6, 3], [1, 5], [0, 4], [5, 4], [5, 5], [5, 7], [1, 2], [0, 4], [2, 2], [7, 8], [4, 6], [2, 2], [1, 6], [3, 9], [9, 3], [1, 7], [2, 9], [4, 2], [6, 9], [4, 7], [0, 5], [4, 2], [4, 5], [3, 8], [7, 9], [1, 7], [0, 3], [9, 7], [6, 8], [6, 0], [2, 1], [8, 0], [7, 4], [4, 3], [7, 2], [6, 7], [7, 1], [3, 8], [0, 4], [4, 0], [0, 8], [1, 2], [8, 4], [6, 5], [2, 1], [1, 9], [8, 9], [0, 2], [9, 1], [9, 8], [4, 9], [5, 6], [2, 3], [4, 7], [4, 6], [8, 6], [0, 0], [4, 8], [8, 1], [6, 8], [4, 9], [7, 9], [6, 2], [9, 8], [1, 8], [4, 2], [2, 3], [2, 4], [0, 9], [5, 3], [7, 2], [3, 9], [4, 6], [9, 4], [9, 3], [8, 0], [7, 4], [3, 2], [4, 6], [4, 9], [5, 5], [7, 7], [0, 1], [9, 3], [1, 1], [8, 0], [0, 4], [2, 1], [7, 4], [2, 4], [9, 9], [7, 1], [1, 8], [6, 6], [1, 0], [3, 6], [3, 7], [4, 2], [2, 0], [7, 9], [5, 7], [6, 8], [2, 4], [9, 0], [9, 4], [0, 2], [3, 4], [6, 0], [2, 6], [3, 9]